chore: add mvc samples vol4 #20245
telerik/ui-for-aspnet-mvc-examples pull request #520
Opened 2024-07-17 05:51 UTC by eyupyusein

2024-07-17 07:50 UTC, IvanDanchev commented
There are a couple of issues: 

1. Errors when you open a view in one of the examples and attempt to build the solution: 

**Error (active)	CS0012	The type 'Expression<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.**

**Error (active)	CS1980	Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?**	

2. The Sample.mdf and Sample_log.ldf files have been modified and committed. 

Ensure that the application builds without errors and do not commit changes to the initial databases, unless you want to add more tables.

2024-07-18 04:53 UTC, eyupyusein commented
I have addressed the comments and fixed the issues.

2024-07-18 06:55 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/DefineCustomKendoHelper/Views/Home/Index.cshtml
> +<br />
- Bootstrap components and description from the MS template do not benefit the example.
- There is a title for PanelBar, but the example shows two grids.

2024-07-18 06:56 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/DefineCustomKendoHelper/Views/Home/Index.cshtml
> +
Add info about each of the two grids that will be visible on the page when the sample is ran,

2024-07-18 06:58 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/DefineCustomKendoHelper/Views/Home/Index.cshtml
Rename the example not to use "Kendo"

2024-07-18 10:09 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorDatabaseImageBrowser/Controllers/HomeController.cs
> +                var thumbnailCreator = new ThumbnailCreator(new FitImageResizer());
ThumbnailCreator is deprecated. Consider an alternative as this will stop working after couple of versions

2024-07-18 10:15 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorDatabaseImageBrowser/Views/Home/Index.cshtml
> +                Kendo UI Editor allows your users to edit HTML in a familiar, user-friendly way.<br />
```suggestion
                Telerik UI for MVC Editor allows your users to edit HTML in a familiar, user-friendly way.<br />
```

2024-07-18 10:23 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorDatabaseImageBrowser/Views/Home/Index.cshtml
Running the sample and clicking on the image icon produces error 500:
![image](https://github.com/user-attachments/assets/679d8f4e-fc95-4bdb-a38f-17cfafb97be1)

2024-07-18 10:26 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorEnterLinebreakShiftEnterParagraph/Views/Home/Index.cshtml
> +                Kendo UI Editor allows your users to edit HTML in a familiar, user-friendly way.<br />
```suggestion
                Telerik UI Editor allows your users to edit HTML in a familiar, user-friendly way.<br />
```

2024-07-18 10:44 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorImportExportKendoWidget/Views/Home/Index.cshtml
> +        $(document).ready(function () {
Initialize the component using Razor

2024-07-18 10:45 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorImportExportKendoWidget/Views/Home/Index.cshtml
> +                },
The first two button look identical when running the example

2024-07-18 10:45 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorUploadImage/Views/Home/Index.cshtml
> +            Kendo UI Editor allows your users to edit HTML in a familiar, user-friendly way.<br />
```suggestion
            Telerik UI Editor allows your users to edit HTML in a familiar, user-friendly way.<br />
```

2024-07-18 12:03 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/Grid/Controllers/EditingCascadingDropDownListController.cs
> +		//}
Is this code used or it can be removed?

2024-07-18 12:25 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditingPopUpMultiselect/Views/Home/Index.cshtml
![image](https://github.com/user-attachments/assets/2009b30b-11cf-4a5e-8516-e789d8190e39)

2024-07-18 12:26 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditingPopUpMultiselect/Controllers/HomeController.cs
The Area appears two times in the changes:
![image](https://github.com/user-attachments/assets/7fd52918-df90-4692-83c4-834740804ced)

2024-07-18 12:36 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditingPopUpServerValidation/Views/Home/Index.cshtml
> +    <li>Click <strong>Update</strong></li>
```suggestion
    <li>Click <strong>Save</strong></li>
```

2024-07-18 12:40 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridExportingExcelMultiple/Controllers/HomeController.cs
Server error when running the sample:
![image](https://github.com/user-attachments/assets/adfcbfbb-4e61-4311-8453-70f7d89d7f2c)

2024-07-18 12:41 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridExportingExcelMultiple/Views/Home/Index.cshtml
> +﻿<button id="export" class="k-button"><span class="k-icon k-i-excel"></span>Export to Excel</button>
No icon for the button:
![image](https://github.com/user-attachments/assets/f7f50dbb-bf8e-4564-a5ca-755726b7a429)

2024-07-18 12:43 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridHierarchyServer/Controllers/HomeController.cs
![image](https://github.com/user-attachments/assets/fb4835dd-10cd-4705-b8ea-9360e019444a)

2024-07-18 13:31 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridTimestamp/Models/Product.cs
Extract each class to a separate file

2024-07-18 13:35 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/MenuSameControllersInDifferentAreas/Views/Home/Index.cshtml
Errors are thrown when clicking the menu items

2024-07-18 14:08 UTC, VicTachev requested changes
All examples using a DB throw an error.
Check other comments as well.

2024-07-24 20:39 UTC, eyupyusein commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditingPopUpMultiselect/Controllers/HomeController.cs
on my side there is only one folder, probably it is some kind of temporary duplicate due to the capital and lower "S"

2024-07-25 05:54 UTC, eyupyusein commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/Grid/Controllers/EditingCascadingDropDownListController.cs
> +		//}
the entire Area folder called Grid will be removed

2024-07-26 08:25 UTC, eyupyusein commented
I have resolved all the comments.

2024-07-29 12:26 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorEnterLinebreakShiftEnterParagraph/Views/Home/Index.cshtml
> +               <img src="http://www.kendoui.com/Image/kendo-logo.png" alt="Editor for ASP.NET MVC logo" style="display:block;margin-left:auto;margin-right:auto;" />
```suggestion
               <img src="https://demos.telerik.com/aspnet-mvc/content/shared/images/site/devcraft-ninja-small.svg" alt="Editor for ASP.NET MVC logo" style="display:block;margin-left:auto;margin-right:auto;" />
```

2024-07-29 12:28 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorEnterLinebreakShiftEnterParagraph/Views/Home/Index.cshtml
> +                Read <a href="http://www.kendoui.com/documentation/introduction.aspx">more details</a> or send us your
```suggestion
                Read <a href="https://docs.telerik.com/aspnet-mvc/introduction">more details</a> or send us your
```

2024-07-29 12:29 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorEnterLinebreakShiftEnterParagraph/Views/Home/Index.cshtml
> +                <a href="http://www.kendoui.com/forums.aspx">feedback</a>!
```suggestion
                <a href="https://www.telerik.com/forums/aspnet-mvc">feedback</a>!
```

2024-07-29 12:32 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/EditorDatabaseImageBrowser/Views/Home/Index.cshtml
> +            </p>
```suggestion
            <p>
                Read <a href="https://docs.telerik.com/aspnet-mvc/introduction">more details</a> or send us your
                <a href="https://www.telerik.com/forums/aspnet-mvc">feedback</a>!
            </p>
```

2024-07-29 12:37 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GanttImportExportUsingMpxj/Views/Home/Index.cshtml
> +	//)
```suggestion
```

2024-07-29 13:31 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditTimespan/GridEditTimespanAreaRegistration.cs
Error thrown when saving:

![image](https://github.com/user-attachments/assets/68c8150d-d657-493f-bafd-32e0c72a909e)

2024-07-29 13:35 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditing3LevelHierarchy/Controllers/EmployeesController.cs
The innermost grid is not editable and should be

2024-07-29 13:44 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditingPopUpMultiSelect/Models/EmployeeViewModel.cs
> +        public DateTime? HireDate { get; set; }
Remove date field - it is not necessary for the example and leads to validation errors when editing

2024-07-29 13:45 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditingPopUpMultiselect/Views/Home/Index.cshtml
> +        debugger;
Remove debugger

2024-07-29 13:51 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridExportingExcelMultiple/Views/Home/Index.cshtml
> +﻿<button id="export" class="k-button k-button-md k-rounded-md k-button-solid k-button-solid-base"><span class="k-icon k-font-icon k-i-excel"></span>Export to Excel</button>
Example does not seem to work. Nothing happens after clicking the button.

2024-07-29 13:55 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridFilterExcelLike/GridFilterExcelLikeAreaRegistration.cs
This example show a scenario with selection, not filtering

2024-07-29 14:01 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridMultiSelect/Views/Home/Index.cshtml
> +        columns.Bound(e => e.HireDate).Format("{0:d}");
Remove date field - it is not necessary for the example and leads to validation errors when editing

2024-07-30 12:16 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridTimestamp/Views/Home/Index.cshtml
> +            columns.Bound(p => p.ProductName);
Add version info to the grid:

```suggestion
            columns.Bound(p => p.ProductName);
            columns.Bound(p => p.RowVersionString);
```

2024-07-30 12:28 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/MenuSameControllersInDifferentAreas/Views/Home/Index.cshtml
Error when clicking "Home"

![image](https://github.com/user-attachments/assets/6b53ccfc-7dff-4144-8aa4-b95626e43994)

2024-07-30 12:31 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/MultiColumnComboBoxEdit/MultiColumnComboBoxEditAreaRegistration.cs
Use PascalCase for the property names

2024-07-30 12:55 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/PanelBarSelectItemInitially/PanelBarHierarchyBindingAreaRegistration.cs
Remove URL from model and from the component. It is not necessary for the example and leads to errors when clicking the PanelBar items  .

2024-07-30 13:08 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerDragAndDrop/Views/Home/Index.cshtml
Item should be selected first and then dragged in order for the example to work. This is not optimal as the behavior is not intuitive.
Update the code logic or at least the description, so it is clearer.

2024-07-30 13:13 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerEditingCustomEditor/Views/Home/EditorTemplates/CustomEditorTemplate.cshtml
Clicking "Save" does not seem to do anything

2024-07-30 13:18 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/ThemeChangeOnClient/ThemeChangeOnClientAreaRegistration.cs
Use version 8.2.1 of the themes

2024-07-30 13:25 UTC, VicTachev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/WindowFormWithAjax/WindowFormWithAjaxAreaRegistration.cs
Clicking "Create" navigates to a new page:
![image](https://github.com/user-attachments/assets/35ff1469-978f-458d-a573-4d916b35ac1d)

2024-08-05 09:47 UTC, eyupyusein commented
Changes are ready.

2024-08-06 08:00 UTC, VicTachev approved these changes

2024-08-06 08:13 UTC, merged