chore: migrate mvc samples vol5 telerik/kendo#20556
telerik/ui-for-aspnet-mvc-examples pull request #521
Opened 2024-07-29 08:28 UTC by eyupyusein

2024-07-30 15:41 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/Bundles/Views/_ViewStart.cshtml
The example should show how to use the kendo ui js and CSS files in bundles. Add a BundleConfig file and add the necessary kendo bundles in it: https://github.com/telerik/ui-for-aspnet-mvc-examples/blob/master/general/KendoAspNetBundles/KendoAspNetBundles/App_Start/BundleConfig.cs
Then use the Area's own Layout to render the bundles: https://github.com/telerik/ui-for-aspnet-mvc-examples/blob/master/general/KendoAspNetBundles/KendoAspNetBundles/Views/Shared/_Layout.cshtml

2024-07-30 15:44 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/Captcha/Views/Home/Index.cshtml
The Captcha's audio does not work.

2024-07-30 15:51 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/ChartSignalR/Views/Home/Index.cshtml
There should be an iframe at the bottom of the Index page in which a Grid declared in different view should be displayed: 
```
<iframe src="@Url.Action("Grid")" style="width: 100%; height: 400px;" frameborder="0"></iframe>
```
https://github.com/telerik/ui-for-aspnet-mvc-examples/blob/master/chart/signalr-bound-chart/KendoUIMVC5/Views/Home/Grid.cshtml

2024-07-30 16:01 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/GridEditingWebApi/Models/ProductsController.cs
The ProductsController.cs file should be in the Area's Controllers folder.

2024-08-01 15:47 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/ODataWebApiWidgets/Views/Home/Index.cshtml
Attempting to update a record results in a failing request: 
Failed to load resource: the server responded with a status of 400 ()

2024-08-01 15:52 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/ODataWebApiWrappers/Views/Home/Index.cshtml
The Editable configuration of the second Grid is not set and on attempting to edit a record nothing happens.

2024-08-01 16:02 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerEditingWebApi/Views/Home/Index.cshtml
The CRUD operations do not work:
PUT https://localhost:44346/SchedulerEditingWebApi/Home/api/Task/25 404 (Not Found)

2024-08-01 16:05 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerGoogleAPI/Views/Home/Index.cshtml
The Scheduler is not loaded with data:
Failed to load resource: the server responded with a status of 400 ()

2024-08-01 16:08 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerSignalRLocalHub/Views/Home/Index.cshtml
No data is loaded in the Scheduler. If you attempt to create a new event, an error is thrown:
Uncaught TypeError: Cannot read properties of undefined (reading 'server')

2024-08-01 16:11 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerSignalRServerFiltering/Views/Home/Index.cshtml
A js exception on loading the page: 
Uncaught Error: The "promise" option must be a Promise.
The Scheduler is non-functional.

2024-08-01 16:15 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerValidatingTimeslot/Views/Home/Index.cshtml
The Read request fails:
Failed to load resource: the server responded with a status of 500 ()

The message for unavailable slots appears when trying to add an event on slots that should be available.

2024-08-01 16:22 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/UploadAmazonS3/Views/Home/Index.cshtml
Remove all the unnecessary tags like **html** and **body** from the view, as well as the old CSS and js references. Only the Upload should be present in the view.

2024-08-01 16:28 UTC, IvanDanchev requested changes
Comments left for issues found in the individual examples

2024-08-06 05:37 UTC, eyupyusein commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerGoogleAPI/Views/Home/Index.cshtml
The sample expects the user to enter his own api key: 
...calendar.google.com/events?key=YourAPI_KEY

2024-08-07 10:06 UTC, eyupyusein commented
All errors have been resolved.

2024-08-07 14:32 UTC, IvanDanchev commented on Telerik.Examples.Mvc/Telerik.Examples.Mvc/Areas/SchedulerValidatingTimeslot/Views/Home/Index.cshtml
After the change, the following exception is thrown on loading the page when the Scheduler sends a request to the Meetings_Read action:
**System.Data.SqlClient.SqlException: Invalid object name 'dbo.MeetingAtendees'.**

2024-08-07 15:00 UTC, IvanDanchev approved these changes
All looks good after the latest commit

2024-08-08 07:50 UTC, merged